openapi: 3.0.1
info:
  title: Car Share Operators
  description: |
    Work-in-progress proposal for car share operators to connect their services to SkedGo's platform.
  version: 0.1.0
servers:
- url: /
paths:
  /vehicle:
    get:
      description: |
        Provides a list of all vehicles (regardless of whether they are currently available or not), including optionally (but highly recommended!) information on prices. Required method.

        Query parameters are optional to request the entire global fleet, or otherwise all parameters are provided to fetch the vehicles in the provided map region.
      parameters:
      - name: north
        in: query
        description: Maximum latitude
        schema:
          type: number
      - name: east
        in: query
        description: Maximum longitude
        schema:
          type: number
      - name: south
        in: query
        description: Minimum latitude
        schema:
          type: number
      - name: west
        in: query
        description: Minimum longitude
        schema:
          type: number
      responses:
        200:
          description: Successful response
          content:
            '*/*':
              schema:
                type: object
                properties:
                  ttl:
                    type: number
                    description: Time To Live for the results in seconds, which is
                      an indicator for SkedGo when to fetch request an update of the
                      fleet information.
                  vehicles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Vehicle'
  /vehicle/{id}/availability:
    get:
      description: |
        Provides availability information for the provided vehicle. Optional method.
      parameters:
      - name: id
        in: path
        description: Unique identifier of this vehicle
        required: true
        schema:
          type: string
      - name: earliest
        in: query
        description: |
          ISO-8601 encoded date for earliest availability information. Should default to "now" if not provided.
        schema:
          type: string
      - name: latest
        in: query
        description: |
          ISO-8601 encoded date for latest availability information.
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Availability'
components:
  schemas:
    Vehicle:
      required:
      - id
      - location
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of this vehicle
        location:
          $ref: '#/components/schemas/Location'
        name:
          type: string
          description: A user-friendly name for the vehicle
        description:
          type: string
          description: A longer user-friendly description of the vehicle
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageInfo'
        details:
          type: object
          properties:
            make:
              type: string
            model:
              type: string
            engine:
              type: string
            automatic:
              type: boolean
            electric:
              type: boolean
            emissions:
              type: number
              description: |
                Emissions in grams CO2 per KM
            seats:
              type: integer
        fuel:
          type: number
          description: Percentage of how full the car's tank / battery currently is
        pricing:
          type: array
          items:
            $ref: '#/components/schemas/Pricing'
        websiteURL:
          type: string
    Location:
      required:
      - lat
      - lng
      type: object
      properties:
        lat:
          type: number
          description: Latitude
        lng:
          type: number
          description: Longitude
        address:
          type: string
    ImageInfo:
      required:
      - height
      - url
      - width
      type: object
      properties:
        width:
          type: number
        height:
          type: number
        url:
          type: string
    Pricing:
      required:
      - cost
      - currency
      - minutes
      type: object
      properties:
        title:
          type: string
          description: Human-friendly title for this price
        currency:
          type: string
          description: Unambiguous currency identifier, e.g., "EUR" or "USD"
        cost:
          type: number
        minutes:
          type: number
          description: Duration in minutes
        includedKM:
          type: number
        costPerKM:
          type: number
      example:
      - title: $8.5 per hour
        cost: 8.5
        currency: AUD
        minutes: 60
      - title: $69 per day
        cost: 69
        currency: AUD
        minutes: 1440
        includedKM: 150
        costPerKM: 0.2
    Availability:
      type: object
      properties:
        arrive:
          type: string
          description: |
            ISO-8601 encoded date. Either this or `depart` is required. If this is provided, `destination` is required.
