swagger: '2.0'

info:
  version: "0.0.1"
  title: Car Share Operators
  description: |
    Work-in-progress proposal for car share operators to connect their services to SkedGo's platform.
  

paths:
  /vehicle:
    get:
      description: |
        Provides a list of all vehicles (regardless of whether they are currently available or not), including optionally (but highly recommended!) information on prices. Required method.
        
        Query parameters are optional to request the entire global fleet, or otherwise all parameters are provided to fetch the vehicles in the provided map region.
      parameters:
        - name: north
          in: query
          type: number
          description: Maximum latitude
          required: false
        - name: east
          in: query
          type: number
          description: Maximum longitude
          required: false
        - name: south
          in: query
          type: number
          description: Minimum latitude
          required: false
        - name: west
          in: query
          type: number
          description: Minimum longitude
          required: false
      
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              ttl:
                type: number
                description: Time To Live for the results in seconds, which is an indicator for SkedGo when to fetch request an update of the fleet information.
              vehicles:
                type: array
                items:
                  $ref: '#/definitions/Vehicle'

  /vehicle/{id}/availability:
    get:
      description: |
        Provides availability information for the provided vehicle. Optional method.
      parameters:
        - name: id
          in: path
          type: string
          description: Unique identifier of this vehicle
          required: true
        - name: earliest
          in: query
          type: string
          description:  |
            ISO-8601 encoded date for earliest availability information. Should default to "now" if not provided.
          required: false
        - name: latest
          in: query
          type: string
          description:  |
            ISO-8601 encoded date for latest availability information.
          required: false
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Availability'
                    
definitions:
  Vehicle:
    properties:
      id:
        type: string
        description: Unique identifier of this vehicle
      location:
        $ref: '#/definitions/Location'
      name:
        type: string
        description: A user-friendly name for the vehicle
      description:
        type: string
        description: A longer user-friendly description of the vehicle
      images:
        type: array
        items:
          $ref: '#/definitions/ImageInfo'
      details:
        type: object
        properties:
          make:
            type: string
          model:
            type: string
          engine:
            type: string
          automatic:
            type: boolean
          electric:
            type: boolean
          emissions:
            type: number
            description: |
              Emissions in grams CO2 per KM
          seats:
            type: integer
      fuel:
        type: number
        description: Percentage of how full the car's tank / battery currently is
      pricing:
        type: array
        items:
          $ref: '#/definitions/Pricing'
      websiteURL:
        type: string
    required:
      - id
      - location

  Location:
    properties:
      lat:
        type: number
        description: Latitude
      lng:
        type: number
        description: Longitude
      address:
        type: string
    required:
      - lat
      - lng

  ImageInfo:
    properties:
      width:
        type: number
      height:
        type: number
      url:
        type: string
    required:
      - width
      - height
      - url

  Pricing:
    properties:
      title:
        type: string
        description: Human-friendly title for this price
      currency:
        type: string
        description: Unambiguous currency identifier, e.g., "EUR" or "USD"
      cost:
        type: number
      minutes:
        type: number
        description: Duration in minutes
      includedKM:
        type: number
        default: 0
      costPerKM:
        type: number
        default: 0
    required:
      - currency
      - cost
      - minutes
    example:
      - title: $8.5 per hour
        cost: 8.5
        currency: AUD
        minutes: 60
      - title: $69 per day
        cost: 69
        currency: AUD
        minutes: 1440
        includedKM: 150
        costPerKM: 0.20
        


  Availability:
    properties:
      arrive:
        type: string
        description: |
          ISO-8601 encoded date. Either this or `depart` is required. If this is provided, `destination` is required.

