swagger: '2.0'

info:
  version: "0.0.1"
  title: Taxi(-like) Operators
  description: |
    Work-in-progress proposal for taxi-like operators to connect their services to SkedGo's platform.
  

# Describe your paths here
paths:
  /coverage:
    get:
      description: |
        Provides a list of all the coverage areas that this operator serves, including optionally (but highly recommended!) information on prices. Optional method, but highly recommended. If not implemented, `/products` should be implemented.
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfAreas
            type: array
            items:
              title: Area
              type: object
              properties:
                polyline:
                  type: string
                  description: Encoded polyline defining coverage area.
                products:
                  type: array
                  items:
                    $ref: '#/definitions/ProductWithPricing'

  /products:
    get:
      description: |
        Provides a list of products for a specific location, including optionally (but highly recommended!) information on prices. Optional method, it is recommended to implement `/coverage` instead.
      parameters:
        - name: lat
          in: query
          type: number
          description: Latitude
          required: true
        - name: lng
          in: query
          type: number
          description: Longitude
          required: true
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductWithPricing'
                    
  /quote:
    post:
      description: |
        Requests a non-binding quote for travelling from one location to another. Optional method, but highly recommended.
      parameters:
        - name: input
          in: body
          schema:
            $ref: '#/definitions/QuoteInput'
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfQuotes
            type: array
            items:
              title: Quote
              type: object
              properties:
                product:
                  $ref: '#/definitions/Product'
                price:
                  title: Price
                  type: object
                  properties:
                    value:
                      type: integer
                      description: Estimated cost in smallest possible local currency
                    currency:
                      type: string
                      description: Unambiguous currency identifier, e.g., "EUR" or "USD"
                pickUpTime:
                  type: string
                  description: The estimated pick-up time as ISO-8601 encoded date.
                pickUpLocation: # If different from requested location.
                  $ref: '#/definitions/Location'
                dropOffLocation: # If different from requested location.
                  $ref: '#/definitions/Location'
                seats:
                  type: number
                  description: Maximum number of available seats for passengers.
              required:
                - product

definitions:
  ProductWithPricing:
    properties:
      product:
        $ref: '#/definitions/Product'
      pricing:
        $ref: '#/definitions/Pricing'
    required:
      - product
      - pricing

  Product:
    properties:
      title:
        type: string
        description: Human-friendly string to describe this product.
      id:
        type: string
    required:
      - title
      - id
        
  Pricing:
    properties:
      currency:
        type: string
        description: Unambiguous currency identifier, e.g., "EUR" or "USD"
      baseCosts:
        type: array
        items:
          title: CostComponent
          type: object
          properties:
            value:
              type: number
            title:
              type: string
      costPerMinute:
        type: number
      costPerKm:
        type: number
      minimumCost:
        type: number
      

  Location:
    properties:
      lat:
        type: number
        description: Latitude
      lng:
        type: number
        description: Longitude
      address:
        type: string
    required:
      - lat
      - lng

  QuoteInput:
    properties:
      origin:
        $ref: '#/definitions/Location'
      destination:
        $ref: '#/definitions/Location'
      depart:
        type: string
        description: ISO-8601 encoded date. Either this or `arrive` is required.
      arrive:
        type: string
        description: |
          ISO-8601 encoded date. Either this or `depart` is required. If this is provided, `destination` is required.
    required:
      - origin
      - destination

